Repository CityRiverSpaces/rcrisp, pull requests merged in 2025-07, with the labels that each got.

#229 Add CRAN badge to README
  README.Rmd
  README.md
Labels: documentation

#255 Standards in category G4
  R/osmdata.R
  R/srr-stats-standards.R
  R/valley.R
Labels: rOpenSci review

#256 Standards in category SP3
  R/segments.R
  R/srr-stats-standards.R
Labels: rOpenSci review

#267 Add package-level documentation
  NEWS.md
  R/rcrisp-package.R
  man/rcrisp-package.Rd
Labels: documentation

#265 Fix issues found with `autotest`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/cache.R
  R/corridor.R
  R/delineate.R
  R/network.R
  R/osmdata.R
  R/segments.R
  R/utils.R
  R/valley.R
  man/as_network.Rd
  man/clean_network.Rd
  man/clear_cache.Rd
  man/delineate.Rd
  man/delineate_corridor.Rd
  man/delineate_segments.Rd
  man/delineate_valley.Rd
  man/dem_to_cog.Rd
  man/flatten_network.Rd
  man/get_dem.Rd
  man/get_osm_streets.Rd
  man/get_osmdata.Rd
  man/get_river_aoi.Rd
  man/get_stac_asset_urls.Rd
  man/get_utm_zone.Rd
  man/load_dem.Rd
  man/osmdata_as_sf.Rd
  man/reproject.Rd
  tests/testthat/test-utils.R
Labels: rOpenSci review

#261 Standards in category G5
  R/cache.R
  R/data.R
  R/exampledata.R
  R/osmdata.R
  R/srr-stats-standards.R
  tests/testthat/helper-exampledata.R
  tests/testthat/test-cache.R
  tests/testthat/test-corridor.R
  tests/testthat/test-delineate.R
  tests/testthat/test-network.R
  tests/testthat/test-osmdata.R
  tests/testthat/test-segments.R
  tests/testthat/test-utils.R
  tests/testthat/test-valley.R
Labels: testing, rOpenSci review

#306 Add valley to package data
  NEWS.md
  data/bucharest_dambovita.rda
Labels: documentation

#305 Move draft vignettes to usecases repo
  .Rbuildignore
  vignettes-drafts/multiple-cities.Rmd
  vignettes-drafts/poi-study-area.Rmd
Labels: documentation

#302 State non-applicability of SP6.6
  R/srr-stats-standards.R
Labels: rOpenSci review

#286 Apply standard SP2.0
  R/srr-stats-standards.R
Labels: rOpenSci review

#301 State non-applicability of SP6.5
  R/srr-stats-standards.R
Labels: rOpenSci review

#304 Fix OSM vignette
  DESCRIPTION
  codemeta.json
  vignettes/vig_02-getting-osm-data.Rmd
Labels: documentation

#296 Apply SP4.0-4.2
  R/corridor.R
  R/delineate.R
  R/exampledata.R
  R/network.R
  R/osmdata.R
  R/riverspace.R
  R/segments.R
  R/sf.R
  R/srr-stats-standards.R
  R/utils.R
Labels: rOpenSci review

#283 State non-applicability of G2.9
  R/srr-stats-standards.R
Labels: rOpenSci review

#287 State compliance with SP2.1
  R/srr-stats-standards.R
Labels: rOpenSci review

#297 State non-applicability of SP5
  R/srr-stats-standards.R
Labels: rOpenSci review

#277 Comply with standard G2.15
  R/srr-stats-standards.R
  R/valley.R
Labels: rOpenSci review

#282 Comply with standard G2.8
  R/srr-stats-standards.R
  R/utils.R
Labels: rOpenSci review

#278 Comply with standard G2.16
  R/corridor.R
  R/osmdata.R
  R/segments.R
  R/srr-stats-standards.R
Labels: rOpenSci review

#276 Match explicit conversions with G2.4 standards
  R/cache.R
  R/network.R
  R/srr-stats-standards.R
  tests/testthat/test-utils.R
Labels: rOpenSci review

#281 State non-applicability of g2.10
  R/corridor.R
  R/network.R
  R/osmdata.R
  R/segments.R
  R/srr-stats-standards.R
  R/utils.R
  R/valley.R
  tests/testthat/test-corridor.R
  tests/testthat/test-network.R
  tests/testthat/test-osmdata.R
  tests/testthat/test-utils.R
  tests/testthat/test-valley.R
  vignettes/vig_04-valley-delineation.Rmd
  vignettes/vig_06-corridor-segmentation.Rmd
Labels: rOpenSci review

#317 Remove SP2.4 from TODO
  R/srr-stats-standards.R
Labels: rOpenSci review

#319 Apply standard SP6.0
  R/srr-stats-standards.R
  tests/testthat/test-utils.R
Labels: rOpenSci review

#315 Compliance to G5.6 - G5.12
  .github/workflows/test-coverage.yaml
  R/corridor.R
  R/segments.R
  R/srr-stats-standards.R
  tests/testthat/helper-extended.R
  tests/testthat/test-corridor.R
  tests/testthat/test-delineate.R
  tests/testthat/test-extended.R
  tests/testthat/test-network.R
  tests/testthat/test-osmdata.R
  tests/testthat/test-segments.R
  tests/testthat/test-utils.R
  tests/testthat/test-valley.R
Labels: rOpenSci review
